### ISSUE TITLE
焦点问题

### ISSUE THREAD

**Issue by anjiuzhe** [AlexMofer/MultiActionTextView#1]
当MultiActionTextView放在可滚动的scrollview底部时，MultiActionTextView设置文本和点击时间后会默认获取焦点，导致scrollview往下拉，试过好多清除焦点等方法都不管用，麻烦大佬有时间抽空帮忙解决下。谢谢！

**Comment by anjiuzhe** [comment]
修改源码已解决！

**Comment by AlexMofer** [comment]
修改了哪儿？我大概猜测到是什么样的现象了，TextView的部分在ScrollView的不可见区域，强制获取焦点后会使其全部显示，因此导致ScrollView滑动。控件设置为强制获取焦点的原因，没记错的话，好象是在列表中会导致其点击效果消失。当这个假装自己一直有焦点的方式其实也不是很优雅，但没发觉其有啥问题，就没再继续深入研究。说说你修改了哪儿，我回头验证一下，得空再好好找一下更好的解决方案。

**Comment by anjiuzhe** [comment]
@AlexMofer 我就是把那些强制获取焦点的代码去掉了，因为我对点击效果没啥要求

**Comment by AlexMofer** [comment]
你要的仅仅是他的着重标记。OK，回头给他增加一个聚焦自我欺骗的开关。

**Comment by anjiuzhe** [comment]
非常感谢！
